// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brspkiauefkwnjuyqijo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyc3BraWF1ZWZrd25qdXlxaWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTQzNjcsImV4cCI6MjA3MjY3MDM2N30.KHu2r3eEvaZ7JVkOBm8bzYoScQvKJMnPdrggalwiDPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});